modLoader = "kotlinforforge"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "GNU General Public License v3.0"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "StackTags"
authors = "linkedto"
description = '''
Adds item tags that set exact max stack sizes (1, 2, 4, 8, 16, 32, 64).
Items in these tags will stack to the specified size across all supported loaders.
'''
logoFile = "icon.png"

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "kotlinforforge"
mandatory = true
versionRange = "[${kotlin_for_forge_version},)"
ordering = "AFTER"
side = "BOTH"